import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Banner from '../../components/banner.js'
import Navbar from '../../components/navbar.js'
import Corousel from '../../components/corousel.js'
import {useContext} from 'react';
import { getVideos } from '../../lib/videoData.js'
import { userContext } from './_app.js'

export async function getServerSideProps(){
  const marvelVideos = await getVideos('marvel%20trailers');
  const dcVideos = await getVideos('dc%20trailers');
  const hotTubVideos = await getVideos('amouranth')

  return {
    props : {marvelVideos, dcVideos , hotTubVideos},
  }

} 

export default function Home({marvelVideos , dcVideos , hotTubVideos}) {

  const {userName , setUserName} = useContext(userContext);
  
  return (
    <div className={styles.body}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar username={userName.email || "sample.email"} firstname={userName.firstname || "Dhruv"} lastname={userName.lastname || "Mittal"}/>
      <Banner title={"Fifty Shades Of Grey"} subTitle={"BDSM is all we want"} imgUrl='/static/grey.jpg'/>
    <div className={styles.sectionWrapper}>
      <Corousel title={"Marvel"} videos={marvelVideos} size="large"/>
      <Corousel title={"DC ki MCBC"} videos={dcVideos} size="small"/>
      <Corousel title={"AMOURNATH FTW"} videos={hotTubVideos} size="medium"/>

      </div>


    </div>
  )
}
