import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Banner from '../../components/banner.js'
import Navbar from '../../components/navbar.js'
import Corousel from '../../components/corousel.js'
import {useContext} from 'react';
import { getVideos } from '../../lib/videoData.js'
import { userContext } from './_app.js'
export async function getServerSideProps({req}){
  const marvelVideos = await getVideos('marvel%20trailers');
  const dcVideos = await getVideos('dc%20trailers');
  const hotTubVideos = await getVideos('amouranth')
  const response = await req.session;
  const user = JSON.stringify(response)

  return {
    props : {marvelVideos, dcVideos , hotTubVideos ,user },
  }

} 

export default function Home({marvelVideos , dcVideos , hotTubVideos ,user }) {
  const userjson = JSON.parse(user)
  return (
    <div className={styles.body}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar username={userjson.email || "sample.email"} firstname={userjson.firstname || "Dhruv"} lastname={userjson.lastname || "Mittal"}/>
      <Banner title={"Fifty Shades Of Grey"} subTitle={"BDSM is all we want"} imgUrl='/static/grey.jpg'/>
    <div className={styles.sectionWrapper}>
      <Corousel title={"Marvel"} videos={marvelVideos} size="large"/>
      <Corousel title={"DC ki MCBC"} videos={dcVideos} size="small"/>
      <Corousel title={"AMOURNATH FTW"} videos={hotTubVideos} size="medium"/>

      </div>


    </div>
  )
}
